spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 3s

      lettuce:
        shutdown-timeout: 200ms
        pool:
          enabled: true
          min-idle: ${REDIS_POOL_MIN_IDLE:2}
          max-idle: ${REDIS_POOL_MAX_IDLE:5}
          max-active: ${REDIS_POOL_MAX_ACTIVE:10}
          max-wait: 1s
