spring:
  application:
    name: post-service
---
app:
  kafka:
    topics:
      post-events: post.events
      user-post-count: user.post.count
  cache:
    post-ttl: 1800
  content:
    max-text-length: 2000
    max-image-size: 10485760 # 10MB
    max-video-size: 52428800 # 50MB
    max-video-duration: 120 # 2 minutes
---
management:
  tracing:
    sampling:
      probability: 1.0 # 100% trace (dev), prod nÃªn 0.1

  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:9411/api/v2/spans}
      transport: http
      timeout: 10s

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
