spring:
  application:
    name: post-service

management:
  tracing:
    sampling:
      probability: 1.0   # 100% trace (dev), prod nÃªn 0.1

  otlp:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      transport: http
      timeout: 10s

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
