spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/super_simple_social_media_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

    pool:
      enabled: true
      initial-size: ${R2DBC_POOL_INITIAL_SIZE:5}
      max-size: ${R2DBC_POOL_MAX_SIZE:20}
      max-idle-time: 30m
      max-life-time: 60m
      acquire-retry: 3

  sql:
    init:
      mode: never

logging:
  level:
    io.r2dbc.postgresql.QUERY: off
    io.r2dbc.postgresql.PARAM: off
