spring:
  application:
    name: user-service

management:
  tracing:
    sampling:
      probability: 1.0 # 100% trace (dev), prod nÃªn 0.1

  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:9411/api/v2/spans}
      transport: http
      timeout: 10s

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
