spring:
  application:
    name: user-service
---
# Application Configuration
app:
  cache:
    user-profile-ttl: 3600 # 1 hour
    user-preferences-ttl: 7200 # 2 hours

  kafka:
    topics:
      user-events: user.events
      user-profile-updated: user.profile.updated
      elasticsearch-sync: elasticsearch.sync

  elasticsearch:
    sync-enabled: true

  lock:
    wait-time: 3000 # ms
    lease-time: 10000 # ms

---
management:
  tracing:
    sampling:
      probability: 1.0 # 100% trace (dev), prod nÃªn 0.1

  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:9411/api/v2/spans}
      transport: http
      timeout: 10s

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
